### PR TITLE
Modified to work under Windows 10

### PR DESCRIPTION
**Pull request by pl71**
Changes that will run code under Win 10 are marked /* pp n */ where n is a number, presently 1 to 7.

### CODE REVIEW

**Comment by Gubaer** [comment]
Thanks for the pull request! I yesterday went to the proposed changes. They are interesting and helpful in resolving the issue with ES modules on the windows problem. Rather than applying the patch immediately, I'd rather wait one or two more weeks. I want to fix the broken unit tests on the windows platform methodically during this time. Unfortunately, I never took care of the scripting plugin on the windows platform, and it shows.

My goal is to fix all the unit tests on the windows platform on the branch [97-esmodules-on-win10-2](https://github.com/Gubaer/josm-scripting-plugin/tree/97-esmodules-on-win10-2) without introducing regressions on the linux platform. This way, I will fix the current problems with CommonJS and ES modules on the windows platform.

**Comment by pl71** [comment]
Hi!

PR is not perfect at all. It may be even dangerous directly applied. I'm new to Java and GraalVM so you may find a better way for the Windows problem.
I've tried to find a working solution only.

Some considerations, you may found them in comments already:
- Path.toString() will put Windows path separators in the resulting string;
- jar.getEntry() is working with forward slashes only;
- isAbsolute() will fail on Windows, I'm using simply relativeModulePath.startsWith("\\")

Regards,
Plamen

     On Wednesday, July 5, 2023 at 12:45:15 AM GMT+3, Gubaer ***@***.***> wrote:  
 
 


Thanks for the pull request! I yesterday went to the proposed changes. They are interesting and helpful in resolving the issue with ES modules on the windows problem. Rather than applying the patch immediately, I'd rather wait one or two more weeks. I want to fix the broken unit tests on the windows platform methodically during this time. Unfortunately, I never took care of the scripting plugin on the windows platform, and it shows.

My goal is to fix all the unit tests on the windows platform on the branch 97-esmodules-on-win10-2 without introducing regressions on the linux platform. This way, I will fix the current problems with CommonJS and ES modules on the windows platform.

**Comment by Gubaer** [comment]
Good idea, thanks! I'll add the hint to the README.

**Comment by pl71** [comment]
Hi,
.\josm.ps1 -josm latest -jdk jdk11 // OK
.\josm.ps1 -josm latest -jdk jdk17 // does't work

See below stack trace:

==== Please provide any additional information below. Attach a screenshot if possible.

{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2023-06-23 15:01:21 +0200 (Fri, 23 Jun 2023)
Revision:18770
Build-Date:2023-06-24 01:30:57
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (18770 bg) Windows 10 64-Bit
Memory Usage: 1024 MB / 2048 MB (981 MB allocated, but free)
Java version: 17.0.7+7-LTS, Microsoft, OpenJDK 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: Cp1251
System property sun.jnu.encoding: Cp1251
Locale info: bg_BG
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djosm.home=<josm.pref>, -Djava.util.logging.config.file=%<user.name>Profile%\git\G-josm-scripting-plugin\testing\windows\logging.properties]

Plugins:
+ scripting

Last errors/warnings:
- 00000.328 W: extended font config - overriding 'filename.Myanmar_Text=mmrtext.ttf' with 'MMRTEXT.TTF'
- 00000.330 W: extended font config - overriding 'filename.Mongolian_Baiti=monbaiti.ttf' with 'MONBAITI.TTF'
- 00000.797 W: java.lang.ExceptionInInitializerError. Причина: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00000.799 W: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00001.048 E: Handled by bug report queue: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
- 00001.165 E: Unable to get Windows build number: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: main (1)
java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry
 at org.openstreetmap.josm.tools.PlatformHookWindows.getCurrentBuild(PlatformHookWindows.java:300)
 at org.openstreetmap.josm.gui.MainApplication.applyLaFWorkarounds(MainApplication.java:1077)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:915)
 at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
 at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
 at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
 at org.openstreetmap.josm.tools.ReflectionUtils.lambda$setObjectsAccessible$0(ReflectionUtils.java:32)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
 at org.openstreetmap.josm.tools.ReflectionUtils.setObjectsAccessible(ReflectionUtils.java:29)
 at org.openstreetmap.josm.tools.WinRegistry.<clinit>(WinRegistry.java:65)
 at org.openstreetmap.josm.tools.PlatformHookWindows.isDotNet45Installed(PlatformHookWindows.java:629)
 at org.openstreetmap.josm.tools.PlatformHookWindows.webRequest(PlatformHookWindows.java:677)
 at org.openstreetmap.josm.tools.PlatformHookWindows.getX509Certificate(PlatformHookWindows.java:363)
 at org.openstreetmap.josm.io.CertificateAmendment.addMissingCertificates(CertificateAmendment.java:231)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:882)
 ... 2 more
}}}

     On Wednesday, July 5, 2023 at 08:32:19 PM GMT+3, Gubaer ***@***.***> wrote:  
 
 


Good idea, thanks! I'll add the hint to the README.

**Comment by pl71** [comment]
josm-snapshot-tested.jar' doesn't exist.

PS C:\Users\User\git\G-josm-scripting-plugin\testing\windows> .\josm.ps1 -josm tested -jdk jdk17Launching JOSM 'tested' with Open JDK for 'jdk17' (without GraalJS)
C:\Users\User\git\G-josm-scripting-plugin\testing\windows\josm.ps1 : JOSM jar 'C:\Users\User\git\G-josm-scripting-plugin\testing\windows\j
osm-snapshot-tested.jar' doesn't exist. Download it first using '.\manage.ps1 download-josm'. Aborting.

Regards
----

    On Thursday, July 6, 2023 at 11:37:25 AM GMT+3, Plamen Penkov ***@***.***> wrote:  
 
  Hi,
.\josm.ps1 -josm latest -jdk jdk11 // OK
.\josm.ps1 -josm latest -jdk jdk17 // does't work

See below stack trace:

==== Please provide any additional information below. Attach a screenshot if possible.

{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2023-06-23 15:01:21 +0200 (Fri, 23 Jun 2023)
Revision:18770
Build-Date:2023-06-24 01:30:57
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (18770 bg) Windows 10 64-Bit
Memory Usage: 1024 MB / 2048 MB (981 MB allocated, but free)
Java version: 17.0.7+7-LTS, Microsoft, OpenJDK 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: Cp1251
System property sun.jnu.encoding: Cp1251
Locale info: bg_BG
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djosm.home=<josm.pref>, -Djava.util.logging.config.file=%<user.name>Profile%\git\G-josm-scripting-plugin\testing\windows\logging.properties]

Plugins:
+ scripting

Last errors/warnings:
- 00000.328 W: extended font config - overriding 'filename.Myanmar_Text=mmrtext.ttf' with 'MMRTEXT.TTF'
- 00000.330 W: extended font config - overriding 'filename.Mongolian_Baiti=monbaiti.ttf' with 'MONBAITI.TTF'
- 00000.797 W: java.lang.ExceptionInInitializerError. Причина: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00000.799 W: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00001.048 E: Handled by bug report queue: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
- 00001.165 E: Unable to get Windows build number: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: main (1)
java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry
 at org.openstreetmap.josm.tools.PlatformHookWindows.getCurrentBuild(PlatformHookWindows.java:300)
 at org.openstreetmap.josm.gui.MainApplication.applyLaFWorkarounds(MainApplication.java:1077)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:915)
 at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
 at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
 at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
 at org.openstreetmap.josm.tools.ReflectionUtils.lambda$setObjectsAccessible$0(ReflectionUtils.java:32)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
 at org.openstreetmap.josm.tools.ReflectionUtils.setObjectsAccessible(ReflectionUtils.java:29)
 at org.openstreetmap.josm.tools.WinRegistry.<clinit>(WinRegistry.java:65)
 at org.openstreetmap.josm.tools.PlatformHookWindows.isDotNet45Installed(PlatformHookWindows.java:629)
 at org.openstreetmap.josm.tools.PlatformHookWindows.webRequest(PlatformHookWindows.java:677)
 at org.openstreetmap.josm.tools.PlatformHookWindows.getX509Certificate(PlatformHookWindows.java:363)
 at org.openstreetmap.josm.io.CertificateAmendment.addMissingCertificates(CertificateAmendment.java:231)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:882)
 ... 2 more
}}}

     On Wednesday, July 5, 2023 at 08:32:19 PM GMT+3, Gubaer ***@***.***> wrote:  
 
 


Good idea, thanks! I'll add the hint to the README.

**Comment by pl71** [comment]
Further to below,
The following script is starting JOSM quite well with ".\josm.ps1 -josm latest -jdk jdk17":
if (!$graalJs) {
    Start-Process `
    -FilePath "$javaBinPath" `
    -ArgumentList `
        '-Xms1g', `
        '-Xmx2g', `
        "-Djosm.home=$josmHome", `
        "-Djava.util.logging.config.file=$loggingPropertiesFile", ` 
        <# "-classpath", $josmJar , `
        "org.openstreetmap.josm.gui.MainApplication" 
        #>
        "-jar josm-latest.jar"
Opposed to original 
"-classpath", $josmJar , `
        "org.openstreetmap.josm.gui.MainApplication" 

which is causing the below error.
Regards,Plamen

    On Thursday, July 6, 2023 at 11:37:25 AM GMT+3, Plamen Penkov ***@***.***> wrote:  
 
  Hi,
.\josm.ps1 -josm latest -jdk jdk11 // OK
.\josm.ps1 -josm latest -jdk jdk17 // does't work

See below stack trace:

==== Please provide any additional information below. Attach a screenshot if possible.

{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2023-06-23 15:01:21 +0200 (Fri, 23 Jun 2023)
Revision:18770
Build-Date:2023-06-24 01:30:57
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (18770 bg) Windows 10 64-Bit
Memory Usage: 1024 MB / 2048 MB (981 MB allocated, but free)
Java version: 17.0.7+7-LTS, Microsoft, OpenJDK 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: Cp1251
System property sun.jnu.encoding: Cp1251
Locale info: bg_BG
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djosm.home=<josm.pref>, -Djava.util.logging.config.file=%<user.name>Profile%\git\G-josm-scripting-plugin\testing\windows\logging.properties]

Plugins:
+ scripting

Last errors/warnings:
- 00000.328 W: extended font config - overriding 'filename.Myanmar_Text=mmrtext.ttf' with 'MMRTEXT.TTF'
- 00000.330 W: extended font config - overriding 'filename.Mongolian_Baiti=monbaiti.ttf' with 'MONBAITI.TTF'
- 00000.797 W: java.lang.ExceptionInInitializerError. Причина: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00000.799 W: java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df
- 00001.048 E: Handled by bug report queue: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
- 00001.165 E: Unable to get Windows build number: java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry. Причина: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: main (1)
java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.josm.tools.WinRegistry
 at org.openstreetmap.josm.tools.PlatformHookWindows.getCurrentBuild(PlatformHookWindows.java:300)
 at org.openstreetmap.josm.gui.MainApplication.applyLaFWorkarounds(MainApplication.java:1077)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:915)
 at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
 at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native long[] java.util.prefs.WindowsPreferences.WindowsRegOpenKey(long,byte[],int) accessible: module java.prefs does not "opens java.util.prefs" to unnamed module @564718df [in thread "main"]
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
 at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
 at org.openstreetmap.josm.tools.ReflectionUtils.lambda$setObjectsAccessible$0(ReflectionUtils.java:32)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
 at org.openstreetmap.josm.tools.ReflectionUtils.setObjectsAccessible(ReflectionUtils.java:29)
 at org.openstreetmap.josm.tools.WinRegistry.<clinit>(WinRegistry.java:65)
 at org.openstreetmap.josm.tools.PlatformHookWindows.isDotNet45Installed(PlatformHookWindows.java:629)
 at org.openstreetmap.josm.tools.PlatformHookWindows.webRequest(PlatformHookWindows.java:677)
 at org.openstreetmap.josm.tools.PlatformHookWindows.getX509Certificate(PlatformHookWindows.java:363)
 at org.openstreetmap.josm.io.CertificateAmendment.addMissingCertificates(CertificateAmendment.java:231)
 at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:882)
 ... 2 more
}}}

     On Wednesday, July 5, 2023 at 08:32:19 PM GMT+3, Gubaer ***@***.***> wrote:  
 
 


Good idea, thanks! I'll add the hint to the README.

**Comment by Gubaer** [comment]
> Further to below, The following script is starting JOSM quite well with ".\josm.ps1 -josm latest -jdk jdk17":  [/snip]

Thanks! See commit 6ecec1ef2cc503edb90c948f0b79090a2cfe38c3.

**Comment by Gubaer** [comment]
I'm closing this pull request. It addresses problems that I have fixed, with your help, in #97.

Thanks for your analysis, contributions, and testing!

**Pull request closed without merging**
