### PR TITLE
I18n and directory structure

### PR DESCRIPTION
**Pull request by floscher**
This PR does two things:
* In a9527b9ed5aa4b61dab2fae1de7f1d2eaf74f67b I moved the directories containing resources and the Java sources to the default locations for a Gradle project:
  * `contrib/` → `src/main/resources/contrib/`
  * `images/` → `src/main/resources/images/`
  * `resources/` → `src/main/resources/resources/`
  * `scripts/` → `src/main/resources/scripts/`
  * `src/` → `src/main/java/`
  * (in the future translations would go into `src/main/po/` or `src/main/mo/`)
* 4cbbd31e4c05f84085305ef029f9787a51eab06c then lets Travis CI send the translatable strings from the Java source code to Transifex. For this to work, you'd need two things:
  * an [API token for Transifex](https://www.transifex.com/user/settings/api/) . Add the token as environment variable `$TRANSIFEX_TOKEN` to [Travis CI](https://travis-ci.org/Gubaer/josm-scripting-plugin/settings).
  * your account on Transifex would need the necessary rights to upload resources to the [JOSM project](https://www.transifex.com/josm/josm/)

### CODE REVIEW

**Comment by Gubaer** [comment]
> your account on Transifex would need the necessary rights to upload resources to the JOSM project
how can I apply for these righst? Are you the owner of the Transifex project who can grant them to me? I use the github identity `Gubaer`  on Transifex too.

**Comment by Gubaer** [comment]
> your account on Transifex would need the necessary rights to upload resources to the JOSM project

how can I apply for these righst? Are you the owner of the Transifex project who can grant them to me? I use the github identity `Gubaer`  on Transifex too.

**Comment by floscher** [comment]
I'll add you as maintainer to the translation team. It was mentioned on the list, that it would be better to use the OpenStreetMap organization instead of the JOSM one. So I'll have to update this PR anyway.

**Comment by floscher** [comment]
You are now a maintainer and should have all necessary rights for https://www.transifex.com/openstreetmap/josm-plugins/ :wink:.

**Comment by Gubaer** [comment]
What'syour experience with travis stages? In contrast with the old travis configuration, the build doesn't run as smoothly with the `.travis.yml` (using stages) on the `floischr-i18n` branch. Do you use stages in other projects too, i.e. for the Mapillary plugin?

**Comment by floscher** [comment]
I only recently started to use them, only for the JOSM plugins that push to transifex.
That's because the Transifex client needs Python (atm in exactly version 3.5) and that was the easiest way to realize that, one stage building with java, then a stage pushing to Transifex with python.
I didn't realize noticable differences, it could be that what you see are general delays on Travis CI, they are having some issues today: https://www.traviscistatus.com/

**Comment by floscher** [comment]
Actually I gave this another thought and concluded, that it would be better to add all JOSM plugins to the JOSM organization on Transifex for the time being. If needed in the future, the project could be transferred as a whole to the Openstreetmap organization.
At the moment there's the licensing concerns with already translated plugins and I'd like to keep the plugins in one place at Transifex.

You are now added to both teams. For the moment I'd prefer https://www.transifex.com/josm/josm/ over https://www.transifex.com/openstreetmap/josm-plugins/ , but let's see how this evolves.

**Comment by Gubaer** [comment]
I don't understand yet how the uploaded `.po` files will end up in the repositories of either of the two teams on Transifex. Shouldn't there be a configuration parameter in `.travis.yml` for target team on Transifex ? I have only one Transifex API key which, given the rights you have  granted to me, should allow me to upload files to either of the teams, correct?

**Pull request merged**
